Tracks/Flask/Lesson 6/webweatherapp/news/models.py
# -*- coding: utf-8 -*-

from webweatherapp.db import db


class News(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    tittle = db.Column(db.String, nullable=False)
    url = db.Column(db.String, unique=True, nullable=False)
    published = db.Column(db.DateTime, nullable=False)
    text = db.Column(db.Text, nullable=True)

    def __repr__(self):
        return '<News {} {}>'.format(self.tittle, self.url)

Tracks/Flask/Lesson 6/webweatherapp/user/models.py
# -*- coding: utf-8 -*-

from flask_login import UserMixin
from werkzeug.security import generate_password_hash, check_password_hash

from webweatherapp.db import db


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(64), index=True, unique=True)
    password = db.Column(db.String(128))
    role = db.Column(db.String(10), index=True)
    email = db.Column(db.String(100), index=True)

    def __repr__(self):
        return '<User {}>'.fromat(self.username)

    def set_password(self, password):
        self.password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

    @property
    def is_admin(self):
        return self.role == 'admin'

Tracks/Flask/Lesson 6/webweatherapp/user/forms.py
# -*- coding: utf-8 -*-

from flask_wtf import FlaskForm
from wtforms import BooleanField, StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired, Email, EqualTo, ValidationError

from webweatherapp.user.models import User


class LoginForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()],
                           render_kw={'class': 'form-control'})
    password = PasswordField('Пароль', validators=[DataRequired()],
                             render_kw={'class': 'form-control'})
    remember = BooleanField('Запомнить меня', default=True,
                            render_kw={'class': 'form-check-input'})
    submit = SubmitField('Отправить',
                         render_kw={'class': 'btn btn-primary'})


class RegistrationForm(FlaskForm):
    username = StringField('Имя пользователя', validators=[DataRequired()], render_kw={'class': 'form-control'})
    email = StringField('Электронная почта', validators=[DataRequired(), Email()], render_kw={'class': 'form-control'})
    password = PasswordField('Пароль', validators=[DataRequired()], render_kw={'class': 'form-control'})
    password2 = PasswordField('Повторите пароль', validators=[DataRequired(), EqualTo('password')], render_kw={'class': 'form-control'})
    submit = SubmitField('Отправить', render_kw={'class': 'btn btn-primary'})

    def validate_username(self, username):
        user_count = User.query.filter_by(username=username.data).count()
        if user_count > 0:
            raise ValidationError(u'Пользователь с таким именем уже существует')

    def validate_email(self, email):
        email_count = User.query.filter_by(email=email.data).count()
        if email_count > 0:
            raise ValidationError('Почта такая уже зарегистрирована')

Tracks/Flask/Lesson 6/webweatherapp/__init__.py
# -*- coding: utf-8 -*-
from flask import Flask
from flask_login import LoginManager
from flask_migrate import Migrate


from webweatherapp.user.models import User
from webweatherapp.user.views import blueprint as user_blueprint
from webweatherapp.admin.views import blueprint as admin_blueprint
from webweatherapp.news.views import blueprint as news_blueprint
from webweatherapp.db import db


def create_app():
    app = Flask(__name__)
    app.config.from_pyfile('config.py')
    db.init_app(app)
    migrate = Migrate(app, db)

    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'user.login'
    app.register_blueprint(user_blueprint)
    app.register_blueprint(admin_blueprint)
    app.register_blueprint(news_blueprint)

    @login_manager.user_loader
    def load_user(user_id):
        return User.query.get(user_id)

    return app

Tracks/Flask/Lesson 6/webweatherapp/admin/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template

from webweatherapp.user.decorators import admin_required

blueprint = Blueprint('admin', __name__, url_prefix='/admin')


@blueprint.route('/')
@admin_required
def admin_index():
    title = 'Панель админки'
    return render_template('admin/homepage.html', admin_title=title)

Tracks/Flask/Lesson 6/webweatherapp/news/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, render_template

import webweatherapp.wetaher_search as weather_search
from webweatherapp.news.models import News

blueprint = Blueprint('news', __name__)


@blueprint.route('/')
def index():
    answer = weather_search.search_weather()
    news = News.query.order_by(News.published.desc()).all()
    print(news)
    return render_template('news/homepage.html', weather_answer=answer,
                           news=news)

Tracks/Flask/Lesson 6/webweatherapp/user/views.py
# -*- coding: utf-8 -*-

from flask import Blueprint, flash, redirect, render_template, url_for
from flask_login import (current_user,
                         login_user, logout_user)

from webweatherapp.db import db
from webweatherapp.user.models import User
from webweatherapp.user.forms import LoginForm, RegistrationForm

blueprint = Blueprint('user', __name__, url_prefix='/users')


@blueprint.route('/login')
def login():
    title = 'Авторизация'
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    else:
        login_form = LoginForm()
        return render_template('user/login.html', page_title=title,
                               form=login_form)


@blueprint.route('/registration')
def registration():
    title = 'Регистрация'
    if current_user.is_authenticated:
        return redirect(url_for('news.index'))
    else:
        registr_form = RegistrationForm()
        return render_template('user/registration.html', page_title=title,
                               form=registr_form)


@blueprint.route('/process_login', methods=['POST'])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter(User.username == form.username.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember.data)
            flash(u'Добро пожаловать!')
            return redirect(url_for('news.index'))

    flash(u'Неправильный логин или пароль')
    return redirect(url_for('user.login'))


@blueprint.route('/process_registration', methods=['POST'])
def process_registration():
    form = RegistrationForm()

    if form.validate_on_submit():
        new_user = User(username=form.username.data, email=form.email.data, role='user')
        new_user.set_password(form.password.data)
        db.session.add(new_user)
        db.session.commit()
        flash(u'Успешная регистрация')
        return redirect(url_for('user.login'))
    else:
        for field, errors in form.errors.items():
            for err in errors:
                flash('Ошибка в поле {}: {}'.format(getattr(form, field).label.text, err))

        return redirect(url_for('user.registration'))


@blueprint.route('/logout')
def logout():
    logout_user()
    flash(u'Вы вышли из учетной записи')
    return redirect(url_for('news.index'))

Tracks/Flask/Lesson 6/webweatherapp/templates/base.html
<!doctype html>
<html lang="ru">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css"
            integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

        <title>Python news</title>
    </head>

    <body>
        {% include 'menu.html' %}
        <div class="container">
            <h1>Новостной сайт</h1>
            {% block content %} {% endblock %}
        </div>
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->
        <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
            integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj"
            crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
            integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
            crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js"
            integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI"
            crossorigin="anonymous"></script>
    </body>
</html>

Tracks/Flask/Lesson 6/webweatherapp/templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#">Новости Python</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="/">Главная страница </a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Что ищем?">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Искать</button>
        </form>
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link" ">Привет, {{ current_user.username }}!</span>
                </li>
                {% if current_user.is_admin %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('admin.admin_index') }}">Админка</a>
                    </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login') }}">Войти</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.registration') }}">Регистрация</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

Tracks/Flask/Lesson 6/webweatherapp/templates/news/homepage.html
{% extends 'base.html' %}

{% block content %}
    <div class="row">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        <div class="col-8">
            <h2>Новости</h2>
            {% if news %}
                {% for el in news %}
                    <p>
                        <a href={{el.url}}>{{el.tittle}}</a>
                        {{el.published.strftime('%d.%m.%Y')}}
                    </p>
                {% endfor %}
            {% else %}
                Новости пока не загрузились
            {% endif %}
        </div>
        <div class="col-4">
            <h2>Погода</h2>
            {% if weather_answer %}
            {{ weather_answer }}
            {% else %}
            Сервис временно не доступен
            {% endif %}
        </div>
    </div>
{% endblock %}

Tracks/Flask/Lesson 6/webweatherapp/templates/user/login.html
{% extends 'base.html' %}

{% block content %}
<h1>{{ page_title }}</h1>
<div class="row">
    <div class="col-8">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}<br>
                {% endfor %}
            </div>
            {% endif %}
        {% endwith %}
        <form action="{{ url_for('user.process_login') }}" method="POST">
            {{ form.hidden_tag() }}
            <div class="form-group">
                {{ form.username.label }}
                {{ form.username() }}
            </div>
            <div class="form-group">
                {{ form.password.label }}
                {{ form.password() }}
            </div>
            <div class="form-group form-check">
                {{ form.remember() }}
                {{ form.remember.label }}
            </div>
            {{ form.submit() }}
        </form>

    </div>
    <div class="col-4">
    </div>
</div>
{% endblock %}

Tracks/Flask/Lesson 6/webweatherapp/templates/user/registration.html
{% extends 'base.html' %}

{% block content %}
    <h1>{{ page_title }}</h1>
    {% with messages = get_flashed_messages() %}
        {% if messages %}
        <div class="alert alert-danger" role="alert">
            {% for message in messages %}
                {{ message }}<br>
            {% endfor %}
        </div>
        {% endif %}
    {% endwith %}
    <div class="row">
        <div class="col-8">
            <form action="{{ url_for('user.process_registration') }}" method="POST">
                {{ form.hidden_tag() }}
                <div class="form-group">
                    {{ form.username.label }}
                    {{ form.username() }}
                </div>
                <div class="form-group">
                    {{ form.email.label }}
                    {{ form.email() }}
                </div>
                <div class="form-group">
                    {{ form.password.label }}
                    {{ form.password() }}
                </div>
                <div class="form-group">
                    {{ form.password2.label }}
                    {{ form.password2() }}
                </div>
                {{ form.submit() }}
            </form>

        </div>
        <div class="col-4">
        </div>
    </div>
{% endblock %}